development:
  encoding: utf8
  adapter: mysql2
  username: root
  password: ""
  host: localhost
  database: bonadea
 
 
test:
  encoding: utf8
  adapter: mysql2
  username: root
  password: ""
  host: localhost
  database: bonadea

