development:
  adapter: mysql2
  username: root
  password: ""
  host: localhost
  database: bonadea
 
 
test:
  adapter: mysql2
  username: root
  password: ""
  host: localhost
  database: bonadea

